spring:
 application:
  name: osms
 datasource:
  url: jdbc:mysql://${database.host}:${database.port}/${database.schema.name}
  username: ${database.user}
  password: ${database.password}
 jpa:
  hibernate:
   ddl-auto: none
 thymeleaf:
  prefix: classpath:ui/templates/
 profiles:
   include: db
